# Basic config
baseURL = "https://www.andrewl.net"
theme = "paper"
defaultContentLanguage = "en"
languageCode = "en"                # zh-Hans
title = ""
copyright = "Â© 2025 Andrew L"
mainSections = ["blog"]

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

disableKinds = ["taxonomy"]

ignoreFiles = ["^notes/", "^content/"]

# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Andrew's Site"
description = "Andrew's Site"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = false
hideRSSLink = false

[params.author]
name = "Andrew L"
email = "andrew@andrewl.net"
fediverse = "@andrewl@mastodon.me.uk"

[[menu.main]]
name = "Things"
pageRef = "/things/"
weight = 30 

[services.rss]
limit = 42

[pagination]
pagerSize = 16
